export default {
  at: "2024-08-07T20:05:51.919Z",
  products: [
    {
      description: "elit mollit minim do",
      name: "esse",
      price: 1107.76,
      tempProperty: undefined,
      activePromoId: 97,
    },
    {
      description: "adipisicing elit eiusmod mollit",
      name: "nulla",
      price: 766.49,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "deserunt cillum in enim",
      name: "do",
      price: 1097.87,
      tempProperty: undefined,
      activePromoId: 96,
    },
    {
      description: "veniam magna duis duis",
      name: "exercitation",
      price: 552.41,
      tempProperty: undefined,
      activePromoId: 14,
    },
    {
      description: "elit incididunt qui esse",
      name: "consequat",
      price: 1184.78,
      tempProperty: undefined,
      activePromoId: null,
    },
    {},
    {},
    {},
    {},
    {},
    {},
    {
      description: "eiusmod non ex eiusmod",
      name: "cupidatat",
      price: 715.79,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "mollit do mollit consectetur",
      name: "mollit",
      price: 1866.97,
      tempProperty: undefined,
      activePromoId: 24,
    },
    {
      description: "qui voluptate minim incididunt",
      name: "ad",
      price: 984.9,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod aliquip veniam cillum",
      name: "duis",
      price: 1775.18,
      tempProperty: undefined,
      activePromoId: 70,
    },
    {
      description: "culpa eu culpa proident",
      name: "ea",
      price: 307.53,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud ullamco nisi amet",
      name: "consequat",
      price: 1446.72,
      tempProperty: undefined,
      activePromoId: 38,
    },
    {},
    {},
    {},
    {},
    {},
    {
      description: "velit aliquip sit minim",
      name: "ad",
      price: 425.16,
      tempProperty: undefined,
      activePromoId: 4,
    },
    {
      description: "elit aute reprehenderit reprehenderit",
      name: "laborum",
      price: 737.12,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "in magna laboris reprehenderit",
      name: "irure",
      price: 1669.29,
      tempProperty: undefined,
      activePromoId: 39,
    },
    {
      description: "id ea ipsum magna",
      name: "eu",
      price: 814.6,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "commodo eiusmod elit amet",
      name: "sunt",
      price: 1122.25,
      tempProperty: undefined,
      activePromoId: 85,
    },
    {
      description: "consectetur ea reprehenderit consequat",
      name: "irure",
      price: 1753.43,
      tempProperty: undefined,
      activePromoId: 53,
    },
    {
      description: "sint minim laborum laborum",
      name: "nostrud",
      price: 1112.28,
      tempProperty: undefined,
      activePromoId: 76,
    },
    {
      description: "sint ex ex deserunt",
      name: "ullamco",
      price: 1628.88,
      tempProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "enim aliqua aliquip qui",
      name: "ea",
      price: 1355.52,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat voluptate laboris elit",
      name: "dolor",
      price: 835.6,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat cillum laboris fugiat",
      name: "tempor",
      price: 825.68,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consequat nisi non minim",
      name: "anim",
      price: 753.48,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eiusmod do ipsum proident",
      name: "esse",
      price: 1071.69,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud laboris occaecat est",
      name: "laboris",
      price: 1731.07,
      tempProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "elit qui reprehenderit non",
      name: "pariatur",
      price: 341.05,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "reprehenderit in commodo fugiat",
      name: "eu",
      price: 713.89,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip qui qui duis",
      name: "aute",
      price: 1750.3,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "quis nisi non irure",
      name: "mollit",
      price: 1532.96,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "consectetur id ad officia",
      name: "deserunt",
      price: 838.98,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "minim laboris do excepteur",
      name: "exercitation",
      price: 1150.03,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "laboris laboris eu non",
      name: "excepteur",
      price: 1850.09,
      tempProperty: undefined,
      activePromoId: 75,
    },
    {
      description: "irure cupidatat aute sit",
      name: "magna",
      price: 1803.1,
      tempProperty: undefined,
      activePromoId: 88,
    },
    {
      description: "nulla fugiat officia quis",
      name: "deserunt",
      price: 403.14,
      tempProperty: undefined,
      activePromoId: 37,
    },
    {
      description: "aute deserunt esse reprehenderit",
      name: "irure",
      price: 1645.93,
      tempProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "eu ipsum consectetur deserunt",
      name: "adipisicing",
      price: 301.18,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat sunt ex non",
      name: "consectetur",
      price: 691.9,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "proident sint ipsum ea",
      name: "magna",
      price: 1283.43,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint enim amet enim",
      name: "Lorem",
      price: 896.68,
      tempProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "minim aliqua incididunt ut",
      name: "ad",
      price: 917.17,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat Lorem cillum nulla",
      name: "nostrud",
      price: 1584.78,
      tempProperty: undefined,
      activePromoId: 61,
    },
    {
      description: "consequat velit sunt proident",
      name: "ex",
      price: 515.94,
      tempProperty: undefined,
      activePromoId: 21,
    },
    {
      description: "enim qui irure qui",
      name: "et",
      price: 547.74,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "tempor duis in incididunt",
      name: "pariatur",
      price: 648.55,
      tempProperty: undefined,
      activePromoId: 77,
    },
    {
      description: "ex esse esse Lorem",
      name: "adipisicing",
      price: 1787.58,
      tempProperty: undefined,
      activePromoId: 53,
    },
    {
      description: "dolore aliquip consectetur culpa",
      name: "id",
      price: 115.8,
      tempProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "cupidatat veniam tempor minim",
      name: "mollit",
      price: 1443.23,
      tempProperty: undefined,
      activePromoId: 13,
    },
    {
      description: "excepteur adipisicing eiusmod sunt",
      name: "nisi",
      price: 213.61,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ullamco dolor deserunt tempor",
      name: "in",
      price: 619.1,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat veniam cillum fugiat",
      name: "aliquip",
      price: 121.55,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat incididunt et veniam",
      name: "dolore",
      price: 1696.1,
      tempProperty: undefined,
      activePromoId: 1,
    },
    {
      description: "magna do irure dolor",
      name: "et",
      price: 624.87,
      tempProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "aliqua ea sunt velit",
      name: "ex",
      price: 1582.74,
      tempProperty: undefined,
      activePromoId: 78,
    },
    {
      description: "incididunt magna labore anim",
      name: "incididunt",
      price: 998.75,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor Lorem do ad",
      name: "qui",
      price: 815.78,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cupidatat ut deserunt mollit",
      name: "non",
      price: 357.02,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "veniam voluptate occaecat fugiat",
      name: "aliqua",
      price: 1885.36,
      tempProperty: undefined,
      activePromoId: 90,
    },
    {
      description: "mollit fugiat occaecat ullamco",
      name: "quis",
      price: 1339.35,
      tempProperty: undefined,
      activePromoId: 2,
    },
    {
      description: "ex ut ipsum excepteur",
      name: "amet",
      price: 1750.67,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sunt cupidatat elit sunt",
      name: "magna",
      price: 723.95,
      tempProperty: undefined,
      activePromoId: 29,
    },
    {
      description: "eiusmod quis est cupidatat",
      name: "excepteur",
      price: 488.98,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud nisi consequat aliqua",
      name: "minim",
      price: 1237.61,
      tempProperty: undefined,
      activePromoId: 33,
    },
    {
      description: "aliquip anim sint nisi",
      name: "pariatur",
      price: 1403.17,
      tempProperty: undefined,
      activePromoId: 42,
    },
    {
      description: "dolore do nostrud anim",
      name: "quis",
      price: 1932.78,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex Lorem ea laborum",
      name: "do",
      price: 1438.11,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "id deserunt eu consequat",
      name: "irure",
      price: 259.6,
      tempProperty: undefined,
      activePromoId: 56,
    },
    {
      description: "adipisicing laborum ad ea",
      name: "eiusmod",
      price: 1347.07,
      tempProperty: undefined,
      activePromoId: 94,
    },
    {
      description: "consectetur ea pariatur adipisicing",
      name: "et",
      price: 187.76,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nostrud quis reprehenderit minim",
      name: "in",
      price: 1702.4,
      tempProperty: undefined,
      activePromoId: 38,
    },
    {
      description: "mollit nostrud laborum nulla",
      name: "velit",
      price: 1065.31,
      tempProperty: undefined,
      activePromoId: 91,
    },
    {
      description: "enim in non sit",
      name: "voluptate",
      price: 664.77,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla exercitation enim id",
      name: "eiusmod",
      price: 1315.89,
      tempProperty: undefined,
      activePromoId: 93,
    },
    {
      description: "id quis proident amet",
      name: "enim",
      price: 1667.65,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "cillum est consectetur esse",
      name: "veniam",
      price: 346.17,
      tempProperty: undefined,
      activePromoId: 80,
    },
    {
      description: "qui enim nisi ex",
      name: "proident",
      price: 1288.46,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "aliquip dolor qui cupidatat",
      name: "aliquip",
      price: 1237.66,
      tempProperty: undefined,
      activePromoId: 16,
    },
    {
      description: "magna sunt quis ut",
      name: "enim",
      price: 1600.12,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "nulla nostrud anim esse",
      name: "consequat",
      price: 1509.55,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "non esse proident incididunt",
      name: "est",
      price: 1158.44,
      tempProperty: undefined,
      activePromoId: 95,
    },
    {
      description: "voluptate velit laborum laborum",
      name: "quis",
      price: 611,
      tempProperty: undefined,
      activePromoId: 79,
    },
    {
      description: "fugiat tempor reprehenderit incididunt",
      name: "minim",
      price: 626.39,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "fugiat dolor proident magna",
      name: "minim",
      price: 1386.01,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "sint dolor in cupidatat",
      name: "adipisicing",
      price: 1178.11,
      tempProperty: undefined,
      activePromoId: 92,
    },
    {
      description: "aute nisi sint amet",
      name: "qui",
      price: 997.21,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "dolor voluptate exercitation velit",
      name: "eu",
      price: 620.73,
      tempProperty: undefined,
      activePromoId: 33,
    },
    {
      description: "commodo elit esse in",
      name: "ea",
      price: 224.59,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "occaecat eiusmod ipsum reprehenderit",
      name: "exercitation",
      price: 1556.13,
      tempProperty: undefined,
      activePromoId: 32,
    },
    {
      description: "veniam cupidatat do magna",
      name: "sint",
      price: 1075.01,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "ex nostrud irure non",
      name: "aute",
      price: 1892.16,
      tempProperty: undefined,
      activePromoId: 82,
    },
    {
      description: "et cupidatat exercitation quis",
      name: "laborum",
      price: 880.68,
      tempProperty: undefined,
      activePromoId: 1,
    },
    {
      description: "non ad magna nostrud",
      name: "consequat",
      price: 264.94,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "do pariatur laborum nisi",
      name: "proident",
      price: 1217.87,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "eu aliqua laboris dolor",
      name: "reprehenderit",
      price: 1812.75,
      tempProperty: undefined,
      activePromoId: 15,
    },
    {
      description: "cupidatat ullamco dolore duis",
      name: "exercitation",
      price: 226.98,
      tempProperty: undefined,
      activePromoId: 71,
    },
    {
      description: "laboris adipisicing sunt ex",
      name: "qui",
      price: 851.69,
      tempProperty: undefined,
      activePromoId: 30,
    },
    {
      description: "dolor elit et excepteur",
      name: "magna",
      price: 1179.98,
      tempProperty: undefined,
      activePromoId: null,
    },
    {
      description: "anim proident est esse",
      name: "qui",
      price: 1848.98,
      tempProperty: undefined,
      activePromoId: 87,
    },
    {
      description: "eu ut commodo do",
      name: "cupidatat",
      price: 1546.82,
      tempProperty: undefined,
      activePromoId: 20,
    },
    {
      description: "dolor labore eiusmod officia",
      name: "et",
      price: 1641.84,
      tempProperty: undefined,
      activePromoId: 18,
    },
    {
      description: "pariatur est elit est",
      name: "qui",
      price: 1498.6,
      tempProperty: undefined,
      activePromoId: null,
    },
  ],
};
